### ISSUE TITLE
Platformer checkpoint visual bug

### ISSUE THREAD

**Issue by sheepdotcom** [blueblock6/TransparentCheckpoints#3]
The checkpoint doesnt bob up and down like it should. This only affects platformer checkpoints not placed by the player and is just a minor visual bug.
The image is a still frame of the checkpoint at the peak of its bob.
Edit: Just realized you arent calling the original function in your `PlayLayer::updateCheckpoints` hook maybe that is why?

![image](https://github.com/user-attachments/assets/db24d0bf-a2ae-40f5-a2f1-bbaf7a719ecb)

**Comment by blueblock6** [comment]
Sorry this took so long, it's finally fixed in [1.0.5](https://github.com/blueblock6/TransparentCheckpoints/releases/tag/1.0.5)
``PlayLayer::updateCheckpoints`` isn't a hook, I added that function.
The solution was simple but it led me to discovering a much bigger problem with the mod which I've only just now figured out how to fix.
In normal mode the checkpoints should look just fine. It still looks weird in practice mode, but because of how the game handles placed checkpoints in platformer practice mode there isn't a great solution.
